### PR TITLE
Add pretty printing without colour

### PR DESCRIPTION
**Pull request by 0rphee**

### CODE REVIEW

**Comment by 0rphee** [comment]
Pinging just in case @tomjaguarpaw

**Comment by tomjaguarpaw** [comment]
Thanks, I wasn't subscribed to the repo (but I am now).

This seems reasonable. Is it for your work including stan into HLS?

It's interesting that `colourista` seems to embed escape codes straight into the string. I was expecting it to use some structured format that we could erase colour from, but maybe not.

We should wait to see if @vrom911 has any objections. She's the project owner and I'm just an assistant. In the meantime can you say more about the use case?

**Comment by 0rphee** [comment]
> This seems reasonable. Is it for your work including stan into HLS?

Precisely. 

> In the meantime can you say more about the use case?

For the hls plugin, initially I used plain `show`'s 😅 for the logging, but I was requested to provide a more friendly output, so I tried using the pretty printer functions here, however, they leave the terminal escape codes in the log files, and thus, here's the PR.

Nevertheless, thinking about it now, (if approved), it may be better to delay a bit the merging of this until I get the green flag that I get to actually use them haha...

**Comment by tomjaguarpaw** [comment]
OK, makes sense. Can I suggest that in the first instance you take the low-tech hacky approach of just stripping everything in the string that occurs between pairs of `\ESC` and `m`[^1]? That will get you the same outcome, but avoid changing this library (which I'm hesitant to do at the moment). 

[^1]: That's the format for terminal escape codes that deal with presentation

**Comment by 0rphee** [comment]
Seems fine :) I'll see what I can do

**Comment by tomjaguarpaw** [comment]
Thanks. Keep me updated on how that goes and then we'll think about what's the best long-term solution.

**Comment by 0rphee** [comment]
Sure, thanks. Your solution works well.

**Pull request closed without merging**
